Class: ""
Displays:
  - Class: rviz/Axes
    Enabled: true
    Length: 2
    Name: map
    Radius: 0.5
    Reference Frame: map
    Value: true
  - Class: rviz/Axes
    Enabled: true
    Length: 1
    Name: base_link
    Radius: 0.30000001192092896
    Reference Frame: base_link
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: false
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: Intensity
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Max Intensity: 128
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: Velodyne
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: false
    Size (Pixels): 2
    Size (m): 2
    Style: Points
    Topic: /lio_sam/deskew/cloud_deskewed
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 0.30000001192092896
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/PointCloud2
    Color: 255; 255; 255
    Color Transformer: Intensity
    Decay Time: 300
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Min Color: 0; 0; 0
    Name: Map(cloud)
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: false
    Size (Pixels): 2
    Size (m): 0.009999999776482582
    Style: Points
    Topic: /lio_sam/deskew/cloud_deskewed
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 1
    Buffer Length: 1
    Class: rviz/Path
    Color: 85; 255; 255
    Enabled: true
    Head Diameter: 0.30000001192092896
    Head Length: 0.20000000298023224
    Length: 0.30000001192092896
    Line Style: Billboards
    Line Width: 0.10000000149011612
    Name: Path(global)
    Offset:
      X: 0
      Y: 0
      Z: 0
    Pose Color: 255; 85; 255
    Pose Style: None
    Radius: 0.029999999329447746
    Shaft Diameter: 0.10000000149011612
    Shaft Length: 0.10000000149011612
    Topic: /lio_sam/mapping/path
    Unreliable: false
    Value: true
  - Alpha: 1
    Buffer Length: 1
    Class: rviz/Path
    Color: 255; 85; 255
    Enabled: true
    Head Diameter: 0.30000001192092896
    Head Length: 0.20000000298023224
    Length: 0.30000001192092896
    Line Style: Billboards
    Line Width: 0.10000000149011612
    Name: Path(local)
    Offset:
      X: 0
      Y: 0
      Z: 0
    Pose Color: 255; 85; 255
    Pose Style: None
    Radius: 0.029999999329447746
    Shaft Diameter: 0.10000000149011612
    Shaft Length: 0.10000000149011612
    Topic: /lio_sam/imu/path
    Unreliable: false
    Value: true
  - Class: rviz/MarkerArray
    Enabled: true
    Marker Topic: /lio_sam/mapping/loop_closure_constraints
    Name: Loop constraint
    Namespaces:
      {}
    Queue Size: 100
    Value: true
Enabled: true
Global Options:
  Background Color: 0; 0; 0
  Default Light: true
  Fixed Frame: map
  Frame Rate: 30
Name: root
Tools:
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Theta std deviation: 0.2617993950843811
    Topic: initialpose
    X std deviation: 0.5
    Y std deviation: 0.5
  - Class: rviz/SetGoal
    Topic: goal
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Theta std deviation: 0.2617993950843811
    Topic: initialpose
    X std deviation: 0.5
    Y std deviation: 0.5
  - Class: rviz/SetGoal
    Topic: goal
Value: true
Views:
  Current:
    Class: rviz/Orbit
    Distance: 54.73565673828125
    Enable Stereo Rendering:
      Stereo Eye Separation: 0.05999999865889549
      Stereo Focal Distance: 1
      Swap Stereo Eyes: false
      Value: false
    Focal Point:
      X: 0
      Y: 0
      Z: 0
    Focal Shape Fixed Size: true
    Focal Shape Size: 0.05000000074505806
    Invert Z Axis: false
    Name: Current View
    Near Clip Distance: 0.009999999776482582
    Pitch: 1.1453979015350342
    Target Frame: <Fixed Frame>
    Value: Orbit (rviz)
    Yaw: 1.6153978109359741
  Saved: ~
